# Generated by Django 5.0.1 on 2024-04-14 14:13

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(max_length=10)),
                ('student_id', models.CharField(default=mainapp.models.generate_student_id, max_length=10, unique=True)),
            ],
        ),
    ]
