# Generated by Django 5.0.4 on 2024-04-14 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_detail',
            old_name='class_name',
            new_name='standard',
        ),
        migrations.AddField(
            model_name='student_detail',
            name='section',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
