# Generated by Django 5.0.4 on 2024-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_class_name_student_detail_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='date_of_birth',
            field=models.DateField(help_text='Use DD/MM/YYYY', verbose_name='Date of Birth'),
        ),
    ]
