# Generated by Django 5.0.4 on 2024-04-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_studentdetail_delete_student_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='grade',
        ),
    ]
