# Generated by Django 5.0.4 on 2024-04-14 15:02

import django.utils.timezone
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_studentdetail_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='standard',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='class_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='grade',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='admission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='student_id',
            field=models.CharField(default=mainapp.models.generate_student_id, max_length=10, unique=True),
        ),
    ]
