# Generated by Django 5.0.4 on 2024-04-14 15:23

import django.utils.timezone
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_studentdetail_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='standard',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='admission_date',
            field=models.DateField(auto_now_add=True, verbose_name='Admission Date'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='student_id',
            field=models.CharField(default=mainapp.models.generate_student_id, max_length=10, unique=True, verbose_name='Student ID'),
        ),
    ]
